sudo: required

services: 
  - docker

before-install:
  - docker build -t mujtabatirmazi/react-app -f Dockerfile.dev .


script:
  - docker run -e CI=true mujtabatirmazi/react-app npm run test -- --coverage